### ISSUE TITLE
Convert 'Batch' to model dict

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/power_perceiver#184]
as described [here](/d/1AaPfg99UQIPofP9B-9S5moc8WjibykKbZNQUSqhciaQ/edit), change Batch object in dict object for model. Hopefully they are clear what shape they should be, and how they should be used

the following keys are needed

- hrvsatellite_actual  (batch_size x 12 historical timesteps x 1 channel x 128 pixels high x 256 pixels wide)
- hrvsatellite_t0_idx  
- hrvsatellite_y_osgb
- hrvsatellite_x_osgb
- hrvsatellite_y_geostationary
- hrvsatellite_x_geostationary
- hrvsatellite_time_utc

- nwp
- nwp_t0_idx
- nwp_target_time_utc
- nwp_init_time_utc
- nwp_y_osgb
- nwp_x_osgb

- pv
- pv_t0_idx
- pv_system_row_number
- pv_y_osgb
- pv_x_osgb
- pv_time_utc

- gsp
- gsp_t0_idx
- gsp_id
- gsp_y_osgb
- gsp_x_osgb
- gsp_time_utc

Optional extra, make this into pydantic object

**Comment by jacobbieker** [comment]
Closing this as using datapipes
